name: Update docker app managementTask

on:
  push:
    branches:
      - 'main'
env:
  AZURE_WEBAPP_NAME: GestTache  # set this to the name of your Azure Web App
  PYTHON_VERSION: '3.8'
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - 
        name: Check
        uses: actions/checkout@v2
      -      
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./sources
          file: ./sources/Dockerfile
          push: true
          tags: ghadafarjeoui/docker:1.0.${{github.run_number}}
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: docker
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/checkout@v3
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}   
